services:
  - type: web
    env: node
    name: face-recognition-backend
    repo: https://github.com/shilishalopez/faceRecognitionAPI.git
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: smart_brain
          property: connectionString

databases:
  - name: smart_brain

# services:
#  - type: pserv
#    name: pgbouncer
#    env: docker
#    plan: standard
#    repo: https://github.com/render-oss/docker-pgbouncer
#    envVars:
#    - key: DATABASE_URL
#      fromDatabase:
#        name: mysite
#        property: connectionString
#    - key: POOL_MODE
#      value: transaction
#    - key: SERVER_RESET_QUERY
#      value: DISCARD ALL
#    - key: MAX_CLIENT_CONN
#      value: 500
#    - key: DEFAULT_POOL_SIZE
#      value: 50